# bundle exec jekyll serve --host=0.0.0.0

title: YaSolR (Yet another Solar Router)
description: Heat water with your Solar Production Excess!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  